name: security
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  dash_shield:
    git:
      url: https://github.com/Ahmad-Ayman/flutter_dash_shield_plugin.git
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0


dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.9.2
  lints: ^5.0.0
  test: ^1.24.0


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)


  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true